// <auto-generated />
using System;
using Bitir.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bitir.Data.Migrations
{
    [DbContext(typeof(BitirMainContext))]
    [Migration("20211115221514_carrier_distribution")]
    partial class carrier_distribution
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.Neighbourhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("LocalityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Neighbourhood","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccount","auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountTypeId = 1,
                            Email = "t@t.com",
                            InsertDate = new DateTime(2021, 11, 16, 1, 15, 14, 387, DateTimeKind.Local).AddTicks(1271),
                            Name = "test",
                            PasswordHash = new byte[] { 75, 38, 103, 93, 54, 164, 91, 214, 177, 69, 155, 54, 221, 0, 66, 114, 68, 131, 158, 134, 230, 85, 202, 71, 14, 100, 4, 1, 138, 47, 175, 246, 237, 137, 222, 148, 79, 223, 87, 85, 187, 97, 197, 91, 107, 215, 210, 40, 227, 177, 85, 202, 107, 238, 160, 102, 218, 98, 115, 6, 131, 72, 131, 172 },
                            PasswordSalt = new byte[] { 195, 134, 211, 147, 227, 7, 20, 99, 45, 186, 45, 142, 186, 73, 236, 44, 231, 83, 80, 43, 49, 169, 80, 167, 244, 229, 246, 127, 168, 255, 139, 37, 156, 21, 140, 155, 52, 87, 139, 237, 84, 113, 200, 194, 6, 210, 206, 145, 150, 34, 153, 74, 89, 118, 81, 16, 156, 221, 220, 64, 185, 43, 247, 6, 135, 254, 195, 183, 92, 235, 112, 126, 122, 43, 167, 11, 210, 60, 38, 180, 24, 164, 161, 255, 159, 34, 147, 231, 71, 129, 208, 143, 187, 199, 66, 49, 77, 7, 136, 13, 18, 98, 200, 196, 60, 150, 63, 71, 118, 225, 14, 139, 92, 236, 7, 123, 73, 244, 107, 51, 88, 83, 210, 224, 67, 150, 176, 91 },
                            Phone = "505",
                            Status = 1,
                            Surname = "test",
                            UpdateDate = new DateTime(2021, 11, 16, 1, 15, 14, 387, DateTimeKind.Local).AddTicks(7599),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccountTypeId = 2,
                            Email = "q@q.com",
                            InsertDate = new DateTime(2021, 11, 16, 1, 15, 14, 387, DateTimeKind.Local).AddTicks(8832),
                            Name = "Vendor",
                            PasswordHash = new byte[] { 75, 38, 103, 93, 54, 164, 91, 214, 177, 69, 155, 54, 221, 0, 66, 114, 68, 131, 158, 134, 230, 85, 202, 71, 14, 100, 4, 1, 138, 47, 175, 246, 237, 137, 222, 148, 79, 223, 87, 85, 187, 97, 197, 91, 107, 215, 210, 40, 227, 177, 85, 202, 107, 238, 160, 102, 218, 98, 115, 6, 131, 72, 131, 172 },
                            PasswordSalt = new byte[] { 195, 134, 211, 147, 227, 7, 20, 99, 45, 186, 45, 142, 186, 73, 236, 44, 231, 83, 80, 43, 49, 169, 80, 167, 244, 229, 246, 127, 168, 255, 139, 37, 156, 21, 140, 155, 52, 87, 139, 237, 84, 113, 200, 194, 6, 210, 206, 145, 150, 34, 153, 74, 89, 118, 81, 16, 156, 221, 220, 64, 185, 43, 247, 6, 135, 254, 195, 183, 92, 235, 112, 126, 122, 43, 167, 11, 210, 60, 38, 180, 24, 164, 161, 255, 159, 34, 147, 231, 71, 129, 208, 143, 187, 199, 66, 49, 77, 7, 136, 13, 18, 98, 200, 196, 60, 150, 63, 71, 118, 225, 14, 139, 92, 236, 7, 123, 73, 244, 107, 51, 88, 83, 210, 224, 67, 150, 176, 91 },
                            Phone = "505",
                            Status = 1,
                            Surname = "test",
                            UpdateDate = new DateTime(2021, 11, 16, 1, 15, 14, 387, DateTimeKind.Local).AddTicks(8837),
                            Username = "vendor"
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Category","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2021, 11, 16, 1, 15, 14, 394, DateTimeKind.Local).AddTicks(8824),
                            Name = "Süt Ürünleri",
                            Status = 1,
                            SubCategoryId = 0,
                            UpdateDate = new DateTime(2021, 11, 16, 1, 15, 14, 394, DateTimeKind.Local).AddTicks(8854)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Günlük İnek Sütü",
                            InsertDate = new DateTime(2021, 11, 16, 1, 15, 14, 398, DateTimeKind.Local).AddTicks(7890),
                            Name = "Süt",
                            Status = 1,
                            UpdateDate = new DateTime(2021, 11, 16, 1, 15, 14, 398, DateTimeKind.Local).AddTicks(7902)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductQuantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("ProductQuantity","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2021, 11, 16, 1, 15, 14, 402, DateTimeKind.Local).AddTicks(8192),
                            ProductId = 1,
                            Quantity = 1m,
                            Status = 1,
                            UnitId = 1,
                            UpdateDate = new DateTime(2021, 11, 16, 1, 15, 14, 402, DateTimeKind.Local).AddTicks(8199)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2021, 11, 16, 1, 15, 14, 402, DateTimeKind.Local).AddTicks(8265),
                            ProductId = 1,
                            Quantity = 2m,
                            Status = 1,
                            UnitId = 1,
                            UpdateDate = new DateTime(2021, 11, 16, 1, 15, 14, 402, DateTimeKind.Local).AddTicks(8266)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ProductStoreId");

                    b.ToTable("ProductStock","product");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStorePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductStoreId");

                    b.ToTable("ProductPrice","product");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product_Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductQuantityId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductQuantityId");

                    b.HasIndex("StoreId");

                    b.ToTable("ProductStore","product");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Unit","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "lt",
                            InsertDate = new DateTime(2021, 11, 16, 1, 15, 14, 401, DateTimeKind.Local).AddTicks(5901),
                            Name = "Litre",
                            Status = 1,
                            UpdateDate = new DateTime(2021, 11, 16, 1, 15, 14, 401, DateTimeKind.Local).AddTicks(5909)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Carrier","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.CarrierDistributionZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("NeighbourhoodId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("NeighbourhoodId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("CarrierDistributionZone","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Carrier_Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("StoreId");

                    b.ToTable("Carrier_Store","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Product_StoreId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("Product_StoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Order","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductStoreId");

                    b.ToTable("OrderDetail","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Store","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Store_UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Store_UserAccount","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.District", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.Neighbourhood", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserAddress", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("UserAddress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserToken", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductQuantity", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product", "Product")
                        .WithMany("ProductQuantity")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Unit", "Unit")
                        .WithMany("ProductQuantities")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStock", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId");

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", "ProductStore")
                        .WithMany()
                        .HasForeignKey("ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStorePrice", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", "ProductStore")
                        .WithMany("ProductStorePrices")
                        .HasForeignKey("ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product_Store", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product", null)
                        .WithMany("ProductStores")
                        .HasForeignKey("ProductId");

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.ProductQuantity", "ProductQuantity")
                        .WithMany("Product_Stores")
                        .HasForeignKey("ProductQuantityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", "Store")
                        .WithMany("ProductStores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.CarrierDistributionZone", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany("CarrierDistributionZones")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.District", "District")
                        .WithMany("CarrierDistributionZones")
                        .HasForeignKey("DistrictId");

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.Neighbourhood", "Neighbourhood")
                        .WithMany("CarrierDistributionZones")
                        .HasForeignKey("NeighbourhoodId");

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.Province", "Province")
                        .WithMany("CarrierDistributionZones")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Carrier_Store", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany("Carrier_Stores")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", "Store")
                        .WithMany("Carrier_Stores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Order", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany("Orders")
                        .HasForeignKey("CarrierId");

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", null)
                        .WithMany("Order")
                        .HasForeignKey("Product_StoreId");

                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", null)
                        .WithMany("Order")
                        .HasForeignKey("StoreId");

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("Order")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.OrderDetail", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", "Product_Store")
                        .WithMany()
                        .HasForeignKey("ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Store_UserAccount", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", "Store")
                        .WithMany("Store_UserAccounts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("Store_UserAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
