// <auto-generated />
using System;
using Bitir.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bitir.Data.Migrations
{
    [DbContext(typeof(BitirMainContext))]
    [Migration("20211104205849_bitirinit")]
    partial class bitirinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccount","auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountTypeId = 1,
                            Email = "t@t.com",
                            InsertDate = new DateTime(2021, 11, 4, 23, 58, 49, 350, DateTimeKind.Local).AddTicks(8767),
                            Name = "test",
                            PasswordHash = new byte[] { 85, 221, 178, 169, 244, 56, 228, 134, 154, 80, 172, 140, 29, 86, 36, 190, 209, 170, 84, 139, 6, 110, 175, 128, 70, 255, 131, 50, 35, 164, 87, 23, 43, 53, 218, 202, 183, 203, 195, 188, 6, 211, 0, 247, 248, 46, 139, 52, 172, 253, 8, 86, 180, 178, 153, 216, 232, 111, 172, 208, 8, 213, 140, 128 },
                            PasswordSalt = new byte[] { 76, 130, 118, 234, 237, 233, 135, 221, 164, 39, 200, 139, 53, 77, 141, 158, 8, 2, 151, 90, 79, 193, 93, 176, 62, 113, 254, 196, 26, 191, 177, 213, 45, 183, 129, 47, 217, 212, 210, 199, 229, 106, 192, 149, 34, 174, 59, 228, 31, 249, 39, 193, 53, 128, 43, 135, 212, 174, 60, 100, 31, 124, 234, 78, 177, 4, 100, 41, 133, 42, 244, 214, 63, 191, 224, 79, 239, 167, 148, 204, 33, 121, 241, 233, 245, 131, 83, 160, 136, 143, 252, 64, 188, 144, 199, 141, 5, 161, 14, 225, 225, 22, 42, 78, 233, 134, 66, 69, 104, 44, 96, 155, 129, 228, 234, 181, 14, 47, 192, 253, 135, 46, 232, 115, 73, 170, 5, 210 },
                            Phone = "505",
                            Status = 1,
                            Surname = "test",
                            UpdateDate = new DateTime(2021, 11, 4, 23, 58, 49, 351, DateTimeKind.Local).AddTicks(4913),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccountTypeId = 2,
                            Email = "q@q.com",
                            InsertDate = new DateTime(2021, 11, 4, 23, 58, 49, 351, DateTimeKind.Local).AddTicks(6076),
                            Name = "Vendor",
                            PasswordHash = new byte[] { 85, 221, 178, 169, 244, 56, 228, 134, 154, 80, 172, 140, 29, 86, 36, 190, 209, 170, 84, 139, 6, 110, 175, 128, 70, 255, 131, 50, 35, 164, 87, 23, 43, 53, 218, 202, 183, 203, 195, 188, 6, 211, 0, 247, 248, 46, 139, 52, 172, 253, 8, 86, 180, 178, 153, 216, 232, 111, 172, 208, 8, 213, 140, 128 },
                            PasswordSalt = new byte[] { 76, 130, 118, 234, 237, 233, 135, 221, 164, 39, 200, 139, 53, 77, 141, 158, 8, 2, 151, 90, 79, 193, 93, 176, 62, 113, 254, 196, 26, 191, 177, 213, 45, 183, 129, 47, 217, 212, 210, 199, 229, 106, 192, 149, 34, 174, 59, 228, 31, 249, 39, 193, 53, 128, 43, 135, 212, 174, 60, 100, 31, 124, 234, 78, 177, 4, 100, 41, 133, 42, 244, 214, 63, 191, 224, 79, 239, 167, 148, 204, 33, 121, 241, 233, 245, 131, 83, 160, 136, 143, 252, 64, 188, 144, 199, 141, 5, 161, 14, 225, 225, 22, 42, 78, 233, 134, 66, 69, 104, 44, 96, 155, 129, 228, 234, 181, 14, 47, 192, 253, 135, 46, 232, 115, 73, 170, 5, 210 },
                            Phone = "505",
                            Status = 1,
                            Surname = "test",
                            UpdateDate = new DateTime(2021, 11, 4, 23, 58, 49, 351, DateTimeKind.Local).AddTicks(6081),
                            Username = "vendor"
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Category","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2021, 11, 4, 23, 58, 49, 357, DateTimeKind.Local).AddTicks(6359),
                            Name = "Süt Ürünleri",
                            Status = 1,
                            SubCategoryId = 0,
                            UpdateDate = new DateTime(2021, 11, 4, 23, 58, 49, 357, DateTimeKind.Local).AddTicks(6383)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Günlük İnek Sütü",
                            InsertDate = new DateTime(2021, 11, 4, 23, 58, 49, 361, DateTimeKind.Local).AddTicks(3986),
                            Name = "Süt",
                            Status = 1,
                            UpdateDate = new DateTime(2021, 11, 4, 23, 58, 49, 361, DateTimeKind.Local).AddTicks(3995)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductQuantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("ProductQuantity","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2021, 11, 4, 23, 58, 49, 365, DateTimeKind.Local).AddTicks(6643),
                            ProductId = 1,
                            Quantity = 1m,
                            Status = 1,
                            UnitId = 1,
                            UpdateDate = new DateTime(2021, 11, 4, 23, 58, 49, 365, DateTimeKind.Local).AddTicks(6651)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2021, 11, 4, 23, 58, 49, 365, DateTimeKind.Local).AddTicks(6713),
                            ProductId = 1,
                            Quantity = 2m,
                            Status = 1,
                            UnitId = 1,
                            UpdateDate = new DateTime(2021, 11, 4, 23, 58, 49, 365, DateTimeKind.Local).AddTicks(6714)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ProductStoreId");

                    b.ToTable("ProductStock","product");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStorePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductStoreId");

                    b.ToTable("ProductPrice","product");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product_Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductQuantityId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductQuantityId");

                    b.HasIndex("StoreId");

                    b.ToTable("ProductStore","product");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.StoreProductByCarrierViewModel", b =>
                {
                    b.Property<int>("ProductStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStock")
                        .HasColumnType("int");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductStockId");

                    b.ToTable("StoreProductByCarrierViewModel");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.StoreProductByStoreViewModel", b =>
                {
                    b.Property<int>("ProductStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStock")
                        .HasColumnType("int");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductStockId");

                    b.ToTable("StoreProductByStoreViewModel");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.StoreProductViewModel", b =>
                {
                    b.Property<int>("ProductStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductPriceId")
                        .HasColumnType("int");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductStockId");

                    b.ToTable("StoreProductViewModel");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Unit","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "lt",
                            InsertDate = new DateTime(2021, 11, 4, 23, 58, 49, 364, DateTimeKind.Local).AddTicks(3912),
                            Name = "Litre",
                            Status = 1,
                            UpdateDate = new DateTime(2021, 11, 4, 23, 58, 49, 364, DateTimeKind.Local).AddTicks(3921)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Carrier","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Carrier_Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("StoreId");

                    b.ToTable("Carrier_Store","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Product_StoreId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Product_StoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Order","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductStoreId");

                    b.ToTable("OrderDetail","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Store","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.StoreOrderViewModel", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("OrderAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderDistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderQuantity")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQuantityId")
                        .HasColumnType("int");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<string>("ProductUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUnitAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("StoreOrderViewModel");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.StoreOrdersView", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("OrderAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderDistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderQuantity")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQuantityId")
                        .HasColumnType("int");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<string>("ProductUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUnitAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("StoreOrdersView","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Store_UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Store_UserAccount","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.District", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserAddress", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("UserAddress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserToken", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductQuantity", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product", "Product")
                        .WithMany("ProductQuantity")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Unit", "Unit")
                        .WithMany("ProductQuantities")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStock", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId");

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", "ProductStore")
                        .WithMany()
                        .HasForeignKey("ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStorePrice", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", "ProductStore")
                        .WithMany("ProductStorePrices")
                        .HasForeignKey("ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product_Store", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product", null)
                        .WithMany("ProductStores")
                        .HasForeignKey("ProductId");

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.ProductQuantity", "ProductQuantity")
                        .WithMany("Product_Stores")
                        .HasForeignKey("ProductQuantityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", "Store")
                        .WithMany("ProductStores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Carrier_Store", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany("Carrier_Stores")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", "Store")
                        .WithMany("Carrier_Stores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Order", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", null)
                        .WithMany("Order")
                        .HasForeignKey("Product_StoreId");

                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", null)
                        .WithMany("Order")
                        .HasForeignKey("StoreId");

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("Order")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.OrderDetail", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", "Product_Store")
                        .WithMany()
                        .HasForeignKey("ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Store_UserAccount", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", "Store")
                        .WithMany("Store_UserAccounts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("Store_UserAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
