// <auto-generated />
using System;
using Bitir.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bitir.Data.Migrations
{
    [DbContext(typeof(BitirMainContext))]
    partial class BitirMainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.Neighbourhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("LocalityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Neighbourhood","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccount","auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountTypeId = 1,
                            Email = "t@t.com",
                            InsertDate = new DateTime(2021, 12, 4, 23, 18, 16, 232, DateTimeKind.Local).AddTicks(6498),
                            Name = "test",
                            PasswordHash = new byte[] { 165, 105, 91, 230, 158, 9, 199, 44, 121, 149, 119, 17, 92, 61, 184, 231, 155, 126, 174, 190, 253, 45, 59, 227, 122, 239, 79, 6, 66, 145, 151, 192, 251, 208, 128, 217, 248, 97, 78, 165, 165, 198, 86, 244, 110, 232, 200, 5, 115, 70, 79, 211, 41, 195, 56, 252, 62, 99, 140, 24, 115, 143, 74, 223 },
                            PasswordSalt = new byte[] { 35, 186, 96, 29, 128, 135, 5, 197, 160, 75, 200, 44, 93, 166, 254, 228, 66, 73, 209, 29, 222, 70, 194, 135, 87, 21, 237, 98, 61, 211, 56, 111, 14, 143, 21, 65, 12, 47, 178, 135, 15, 203, 194, 39, 105, 190, 172, 185, 114, 12, 235, 225, 146, 82, 200, 180, 228, 184, 44, 137, 12, 131, 174, 105, 178, 187, 252, 243, 63, 249, 187, 203, 43, 217, 52, 246, 147, 146, 97, 93, 160, 78, 229, 45, 243, 159, 215, 165, 193, 126, 12, 203, 194, 37, 171, 112, 94, 117, 17, 83, 44, 132, 41, 124, 202, 130, 199, 193, 59, 192, 28, 91, 125, 102, 216, 186, 158, 148, 181, 1, 3, 57, 217, 34, 149, 115, 34, 6 },
                            Phone = "505",
                            Status = 1,
                            Surname = "test",
                            UpdateDate = new DateTime(2021, 12, 4, 23, 18, 16, 233, DateTimeKind.Local).AddTicks(2618),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccountTypeId = 2,
                            Email = "q@q.com",
                            InsertDate = new DateTime(2021, 12, 4, 23, 18, 16, 233, DateTimeKind.Local).AddTicks(3795),
                            Name = "Vendor",
                            PasswordHash = new byte[] { 165, 105, 91, 230, 158, 9, 199, 44, 121, 149, 119, 17, 92, 61, 184, 231, 155, 126, 174, 190, 253, 45, 59, 227, 122, 239, 79, 6, 66, 145, 151, 192, 251, 208, 128, 217, 248, 97, 78, 165, 165, 198, 86, 244, 110, 232, 200, 5, 115, 70, 79, 211, 41, 195, 56, 252, 62, 99, 140, 24, 115, 143, 74, 223 },
                            PasswordSalt = new byte[] { 35, 186, 96, 29, 128, 135, 5, 197, 160, 75, 200, 44, 93, 166, 254, 228, 66, 73, 209, 29, 222, 70, 194, 135, 87, 21, 237, 98, 61, 211, 56, 111, 14, 143, 21, 65, 12, 47, 178, 135, 15, 203, 194, 39, 105, 190, 172, 185, 114, 12, 235, 225, 146, 82, 200, 180, 228, 184, 44, 137, 12, 131, 174, 105, 178, 187, 252, 243, 63, 249, 187, 203, 43, 217, 52, 246, 147, 146, 97, 93, 160, 78, 229, 45, 243, 159, 215, 165, 193, 126, 12, 203, 194, 37, 171, 112, 94, 117, 17, 83, 44, 132, 41, 124, 202, 130, 199, 193, 59, 192, 28, 91, 125, 102, 216, 186, 158, 148, 181, 1, 3, 57, 217, 34, 149, 115, 34, 6 },
                            Phone = "505",
                            Status = 1,
                            Surname = "test",
                            UpdateDate = new DateTime(2021, 12, 4, 23, 18, 16, 233, DateTimeKind.Local).AddTicks(3801),
                            Username = "vendor"
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken","auth");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Category","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2021, 12, 4, 23, 18, 16, 240, DateTimeKind.Local).AddTicks(1420),
                            Name = "Süt Ürünleri",
                            Status = 1,
                            SubCategoryId = 0,
                            UpdateDate = new DateTime(2021, 12, 4, 23, 18, 16, 240, DateTimeKind.Local).AddTicks(1449)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Günlük İnek Sütü",
                            InsertDate = new DateTime(2021, 12, 4, 23, 18, 16, 244, DateTimeKind.Local).AddTicks(501),
                            Name = "Süt",
                            Status = 1,
                            UpdateDate = new DateTime(2021, 12, 4, 23, 18, 16, 244, DateTimeKind.Local).AddTicks(519)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductQuantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("ProductQuantity","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2021, 12, 4, 23, 18, 16, 248, DateTimeKind.Local).AddTicks(1417),
                            ProductId = 1,
                            Quantity = 1m,
                            Status = 1,
                            UnitId = 1,
                            UpdateDate = new DateTime(2021, 12, 4, 23, 18, 16, 248, DateTimeKind.Local).AddTicks(1427)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2021, 12, 4, 23, 18, 16, 248, DateTimeKind.Local).AddTicks(1492),
                            ProductId = 1,
                            Quantity = 2m,
                            Status = 1,
                            UnitId = 1,
                            UpdateDate = new DateTime(2021, 12, 4, 23, 18, 16, 248, DateTimeKind.Local).AddTicks(1494)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ProductStoreId");

                    b.ToTable("ProductStock","product");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStorePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductStoreId");

                    b.ToTable("ProductPrice","product");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product_Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductQuantityId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductQuantityId");

                    b.HasIndex("StoreId");

                    b.ToTable("ProductStore","product");
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Unit","product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "lt",
                            InsertDate = new DateTime(2021, 12, 4, 23, 18, 16, 246, DateTimeKind.Local).AddTicks(8910),
                            Name = "Litre",
                            Status = 1,
                            UpdateDate = new DateTime(2021, 12, 4, 23, 18, 16, 246, DateTimeKind.Local).AddTicks(8924)
                        });
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Carrier","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.CarrierDistributionZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("NeighbourhoodId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("NeighbourhoodId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("CarrierDistributionZone","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Carrier_Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("StoreId");

                    b.ToTable("Carrier_Store","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Product_StoreId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<int>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("Product_StoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Order","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductStoreId");

                    b.ToTable("OrderDetail","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Store","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Store_UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Store_UserAccount","sales");
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.District", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.Neighbourhood", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserAddress", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("UserAddress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.AuthModuleEntities.UserToken", b =>
                {
                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductQuantity", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product", "Product")
                        .WithMany("ProductQuantity")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Unit", "Unit")
                        .WithMany("ProductQuantities")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStock", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId");

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", "ProductStore")
                        .WithMany()
                        .HasForeignKey("ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.ProductStorePrice", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", "ProductStore")
                        .WithMany("ProductStorePrices")
                        .HasForeignKey("ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.ProductModuleEntities.Product_Store", b =>
                {
                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product", null)
                        .WithMany("ProductStores")
                        .HasForeignKey("ProductId");

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.ProductQuantity", "ProductQuantity")
                        .WithMany("Product_Stores")
                        .HasForeignKey("ProductQuantityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", "Store")
                        .WithMany("ProductStores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.CarrierDistributionZone", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany("CarrierDistributionZones")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.District", "District")
                        .WithMany("CarrierDistributionZones")
                        .HasForeignKey("DistrictId");

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.Neighbourhood", "Neighbourhood")
                        .WithMany("CarrierDistributionZones")
                        .HasForeignKey("NeighbourhoodId");

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.Province", "Province")
                        .WithMany("CarrierDistributionZones")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Carrier_Store", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany("Carrier_Stores")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", "Store")
                        .WithMany("Carrier_Stores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Order", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Carrier", "Carrier")
                        .WithMany("Orders")
                        .HasForeignKey("CarrierId");

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", null)
                        .WithMany("Order")
                        .HasForeignKey("Product_StoreId");

                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", null)
                        .WithMany("Order")
                        .HasForeignKey("StoreId");

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("Order")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.OrderDetail", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.ProductModuleEntities.Product_Store", "Product_Store")
                        .WithMany()
                        .HasForeignKey("ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Shared.Entities.SalesModuleEntities.Store_UserAccount", b =>
                {
                    b.HasOne("Module.Shared.Entities.SalesModuleEntities.Store", "Store")
                        .WithMany("Store_UserAccounts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Shared.Entities.AuthModuleEntities.UserAccount", "UserAccount")
                        .WithMany("Store_UserAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
